[package]
name = "rust-guessing-game"
version = "0.1.0"
authors = ["Junsu Shin <junsushin4546@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
